/*
 * ANIMAL CARE PROJECT
 * File: frmReporte.java
 * Description: Form responsible for generating and displaying system reports and listings.
 *
 * Documentation added solely for academic and maintenance purposes.
 * The logic, instructions, and behavior of the original code were not modified.
 */

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;

/**
 * Report window required by the project rubric.
 * Every report is generated by relating the original dynamic lists;
 * no additional structure is created to duplicate all the information.
 */
public class frmReporte extends JFrame {

    // Fields kept for compatibility with the existing IntelliJ .form file.
    public JPanel panelPrincipal;
    private JTextPane txtReporte;
    private JButton btnSalir;

    private final List<ConsultaMedica> listConsulta;
    private final List<Mascota> listMascota;
    private final List<Propietario> listPropietario;
    private final List<Veterinario> listVeterinario;
    private final List<Especialidad> listEspecialidad;

    private JTable tablaConsultas;
    private JTable tablaMascotas;
    private JTable tablaMayoresCinco;
    private JCheckBox chkSoloActivas;
    private JLabel lblResumenMayores;

    public frmReporte(List<ConsultaMedica> listConsulta, List<Mascota> listMascota, List<Propietario> listPropietario, List<Veterinario> listVeterinario, List<Especialidad> listEspecialidad) {
        this.listConsulta = listConsulta;
        this.listMascota = listMascota;
        this.listPropietario = listPropietario;
        this.listVeterinario = listVeterinario;
        this.listEspecialidad = listEspecialidad;

        setTitle("Animal Care | Reportes y Listados");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        JPanel interfazReportes = crearInterfazReportes();
        setContentPane(interfazReportes);
        AnimalCareTheme.apply(this, interfazReportes);
        setSize(1050, 620);
        setLocationRelativeTo(null);
        actualizarReportes();
    }

    /** Builds a clear report interface using several Swing component types. */
    private JPanel crearInterfazReportes() {
        JPanel raiz = new JPanel(new BorderLayout(8, 8));
        raiz.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        JLabel titulo = new JLabel("LISTADOS GENERALES - ANIMAL CARE", SwingConstants.CENTER);
        raiz.add(titulo, BorderLayout.NORTH);

        JTabbedPane pestañas = new JTabbedPane();

        tablaConsultas = crearTabla(new String[]{
                "N° Consulta", "Fecha", "Nombre Mascota", "Nombre Propietario",
                "Veterinario", "Especialidad", "Diagnóstico", "Costo"
        });
        pestañas.addTab("Consultas", new JScrollPane(tablaConsultas));

        JPanel panelMascotas = new JPanel(new BorderLayout(5, 5));
        chkSoloActivas = new JCheckBox("Mostrar únicamente mascotas activas");
        chkSoloActivas.addActionListener(e -> cargarMascotasGenerales());
        panelMascotas.add(chkSoloActivas, BorderLayout.NORTH);
        tablaMascotas = crearTabla(new String[]{
                "Código", "Nombre", "Especie", "Propietario", "Estado"
        });
        panelMascotas.add(new JScrollPane(tablaMascotas), BorderLayout.CENTER);
        pestañas.addTab("Mascotas", panelMascotas);

        JPanel panelMayores = new JPanel(new BorderLayout(5, 5));
        lblResumenMayores = new JLabel();
        panelMayores.add(lblResumenMayores, BorderLayout.NORTH);
        tablaMayoresCinco = crearTabla(new String[]{
                "Código", "Nombre", "Especie", "Edad", "Propietario", "Estado"
        });
        panelMayores.add(new JScrollPane(tablaMayoresCinco), BorderLayout.CENTER);
        pestañas.addTab("Mascotas > 5 años", panelMayores);

        raiz.add(pestañas, BorderLayout.CENTER);

        JPanel pie = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        JButton btnActualizar = new JButton("Actualizar");
        JButton btnCerrar = new JButton("Salir");
        btnActualizar.addActionListener(e -> actualizarReportes());
        btnCerrar.addActionListener(e -> dispose());
        pie.add(btnActualizar);
        pie.add(btnCerrar);
        raiz.add(pie, BorderLayout.SOUTH);

        return raiz;
    }

    private JTable crearTabla(String[] columnas) {
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        JTable tabla = new JTable(modelo);
        tabla.setAutoCreateRowSorter(true);
        tabla.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        return tabla;
    }

    /** Refreshes the three reports from the original lists. */
    private void actualizarReportes() {
        cargarConsultasGenerales();
        cargarMascotasGenerales();
        cargarMascotasMayoresCinco();
    }

    /**
     * Required general consultation report.
     * Data is related at display time using the identifiers stored in ConsultaMedica.
     */
    private void cargarConsultasGenerales() {
        DefaultTableModel modelo = (DefaultTableModel) tablaConsultas.getModel();
        modelo.setRowCount(0);

        for (ConsultaMedica c : listConsulta) {
            modelo.addRow(new Object[]{
                    c.getNumConsulta(),
                    c.getFecha(),
                    obtenerNombreMascota(c.getCodMascota()),
                    obtenerNombrePropietario(c.getIdPropietario()),
                    obtenerNombreVeterinario(c.getIdVeterinario()),
                    obtenerNombreEspecialidad(c.getCodEspecialidad()),
                    c.getDiagnostico(),
                    c.getCosto()
            });
        }
    }

    /** Required general pet report. */
    private void cargarMascotasGenerales() {
        DefaultTableModel modelo = (DefaultTableModel) tablaMascotas.getModel();
        modelo.setRowCount(0);

        for (Mascota m : listMascota) {
            if (chkSoloActivas.isSelected() && !m.isEstado()) {
                continue;
            }
            modelo.addRow(new Object[]{
                    m.getCodMascota(),
                    m.getNomMascota(),
                    m.getEspecie(),
                    obtenerNombrePropietario(m.getIdPropietario()),
                    m.isEstado() ? "Activo" : "Inactivo"
            });
        }
    }

    /** Required report containing only pets older than five years. */
    private void cargarMascotasMayoresCinco() {
        DefaultTableModel modelo = (DefaultTableModel) tablaMayoresCinco.getModel();
        modelo.setRowCount(0);

        for (Mascota m : listMascota) {
            if (m.getEdad() > 5) {
                modelo.addRow(new Object[]{
                        m.getCodMascota(),
                        m.getNomMascota(),
                        m.getEspecie(),
                        m.getEdad(),
                        obtenerNombrePropietario(m.getIdPropietario()),
                        m.isEstado() ? "Activo" : "Inactivo"
                });
            }
        }

        // Recursion is intentionally used to satisfy the POO/recursion rubric item.
        int total = new Mascota().contarMayoresDeCincoRecursivo(listMascota, 0);
        lblResumenMayores.setText("Total de mascotas mayores de 5 años: " + total);
    }

    private String obtenerNombreMascota(String codigo) {
        for (Mascota m : listMascota) {
            if (m.getCodMascota().equalsIgnoreCase(codigo)) {
                return m.getNomMascota();
            }
        }
        return "No encontrada";
    }

    private String obtenerNombrePropietario(String id) {
        for (Propietario p : listPropietario) {
            if (p.getIdPersona().equalsIgnoreCase(id)) {
                return p.getNomPersona();
            }
        }
        return "No encontrado";
    }

    private String obtenerNombreEspecialidad(String codigo) {
        for (Especialidad e : listEspecialidad) {
            if (e.getCodEspecialidad().equalsIgnoreCase(codigo)) {
                return e.getNomEspecialidad();
            }
        }
        return "No encontrada";
    }

    private String obtenerNombreVeterinario(String id) {
        for (Veterinario v : listVeterinario) {
            if (v.getIdPersona().equalsIgnoreCase(id)) {
                return v.getNomPersona();
            }
        }
        return "No encontrado";
    }
}
